In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
from sklearn import datasets

In [4]:
data = datasets.load_boston()

In [6]:
dir(data)

['DESCR', 'data', 'data_module', 'feature_names', 'filename', 'target']

In [13]:
df = pd.DataFrame(data.data,columns=data.feature_names)

In [15]:
df['target'] = data.target

In [17]:
df.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,target
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3.0,222.0,18.7,394.12,5.21,28.7
6,0.08829,12.5,7.87,0.0,0.524,6.012,66.6,5.5605,5.0,311.0,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,19.15,27.1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0.0,0.524,6.004,85.9,6.5921,5.0,311.0,15.2,386.71,17.10,18.9

In [18]:
df.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
target     0
dtype: int64

In [34]:
X = df.iloc[: , :-1]
y = df.iloc[: , -1]

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [37]:
from sklearn.linear_model import LinearRegression

In [38]:
from sklearn.metrics import r2_score

### Linear Regression

In [39]:
reg = LinearRegression()
reg.fit(X_train,y_train)
y_test_pred = reg.predict(X_test)
print("R2_score value = ",r2_score(y_test,y_test_pred))
checking = pd.DataFrame()
checking["column_names"] = X_train.columns
checking["coeffcient_values"] = reg.coef_
checking

R2_score value =  0.7261570836552476

   column_names  coeffcient_values
0          CRIM          -0.128750
1            ZN           0.037823
2         INDUS           0.058211
3          CHAS           3.238668
4           NOX         -16.169812
5            RM           3.902051
6           AGE          -0.012851
7           DIS          -1.422224
8           RAD           0.234854
9           TAX          -0.008213
10      PTRATIO          -0.928722
11            B           0.011770
12        LSTAT          -0.547566

### Ridge Regression

In [40]:
from sklearn.linear_model import Ridge
reg1 = Ridge(alpha=0.5)
reg1.fit(X_train,y_train)
y_test_pred = reg1.predict(X_test)
print("R2_score value = ",r2_score(y_test,y_test_pred))
checking = pd.DataFrame()
checking["column_names"] = X_train.columns
checking["coeffcient_values"] = reg.coef_
checking['Ridge_coef_values'] = reg1.coef_
checking

R2_score value =  0.7229361801908383

   column_names  coeffcient_values  Ridge_coef_values
0          CRIM          -0.128750          -0.124591
1            ZN           0.037823           0.038469
2         INDUS           0.058211           0.034918
3          CHAS           3.238668           3.116315
4           NOX         -16.169812         -10.753667
5            RM           3.902051           3.911982
6           AGE          -0.012851          -0.017433
7           DIS          -1.422224          -1.341809
8           RAD           0.234854           0.222522
9           TAX          -0.008213          -0.008706
10      PTRATIO          -0.928722          -0.867973
11            B           0.011770           0.011923
12        LSTAT          -0.547566          -0.559961

### Lasso Regression

In [41]:
from sklearn.linear_model import Lasso
reg2 = Lasso(alpha=0.5)
reg2.fit(X_train,y_train)
y_test_pred = reg2.predict(X_test)
print("R2_score value = ",r2_score(y_test,y_test_pred))
checking = pd.DataFrame()
checking["column_names"] = X_train.columns
checking["coeffcient_values"] = reg.coef_
checking['Ridge_coef_values'] = reg1.coef_
checking["Lasso_coefficient_values"] = reg2.coef_

checking

R2_score value =  0.6983027905015838

,column_names,coeffcient_values,Ridge_coef_values,Lasso_coefficient_values
0,CRIM,-0.128750,-0.124591,-0.102550
1,ZN,0.037823,0.038469,0.038882
2,INDUS,0.058211,0.034918,-0.000000
3,CHAS,3.238668,3.116315,0.000000
4,NOX,-16.169812,-10.753667,-0.000000
5,RM,3.902051,3.911982,2.577743
6,AGE,-0.012851,-0.017433,-0.004785
7,DIS,-1.422224,-1.341809,-0.916826
8,RAD,0.234854,0.222522,0.208420
9,TAX,-0.008213,-0.008706,-0.010149
10,PTRATIO,-0.928722,-0.867973,-0.738745
11,B,0.011770,0.011923,0.012080
12,LSTAT,-0.547566,-0.559961,-0.695736

In [42]:
### The coefficient value which are zero we can remove those column for training ML Models